// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBndvFhEUs1h7Fbx7wwAW62HFPrpplWvLU',
    appId: '1:650434704290:web:903496db4f7d6e6262b8fb',
    messagingSenderId: '650434704290',
    projectId: 'water-quality-monitor-app',
    authDomain: 'water-quality-monitor-app.firebaseapp.com',
    storageBucket: 'water-quality-monitor-app.firebasestorage.app',
    measurementId: 'G-6NJHND0NJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI-5rOW9AqqYLNgHQxwRh9YZagW_YYZps',
    appId: '1:650434704290:android:0b904eab0ab0752c62b8fb',
    messagingSenderId: '650434704290',
    projectId: 'water-quality-monitor-app',
    storageBucket: 'water-quality-monitor-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuTXCc79-WOs7klhkmbzRfMMoZRspIpik',
    appId: '1:650434704290:ios:a478354c5c72a12962b8fb',
    messagingSenderId: '650434704290',
    projectId: 'water-quality-monitor-app',
    storageBucket: 'water-quality-monitor-app.firebasestorage.app',
    iosBundleId: 'com.example.waterMonitorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuTXCc79-WOs7klhkmbzRfMMoZRspIpik',
    appId: '1:650434704290:ios:a478354c5c72a12962b8fb',
    messagingSenderId: '650434704290',
    projectId: 'water-quality-monitor-app',
    storageBucket: 'water-quality-monitor-app.firebasestorage.app',
    iosBundleId: 'com.example.waterMonitorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBndvFhEUs1h7Fbx7wwAW62HFPrpplWvLU',
    appId: '1:650434704290:web:f41a569d5b9f2fd862b8fb',
    messagingSenderId: '650434704290',
    projectId: 'water-quality-monitor-app',
    authDomain: 'water-quality-monitor-app.firebaseapp.com',
    storageBucket: 'water-quality-monitor-app.firebasestorage.app',
    measurementId: 'G-CYGXG81W7J',
  );
}
